### ISSUE TITLE
No output?

### ISSUE THREAD

**Issue by FranklinChen** [paf31/purescript-graphics-vis#3]
I'm on macOS Sierra, running PureScript 0.11.5. The Web page doesn't seem to display anything for me.

```
$ pulp psci -- --port 8080
PSCi, version 0.11.5
Type :? for help

Bundling JavaScript...
Serving http://localhost:8080/. Waiting for connections...
> import Graphics.Vis.Example
> animate scene
anonymous/<@http://localhost:8080/js/index.js line 31 > Function:11:5
anonymous@http://localhost:8080/js/index.js line 31 > Function:4:2
evaluate@http://localhost:8080/js/index.js:31:5
reload/<@http://localhost:8080/js/index.js:41:30
get/<@http://localhost:8080/js/index.js:4:9

>
```

**Comment by paf31** [comment]
Are you opening the browser after the `Serving http://localhost:8080/` message?

**Comment by paf31** [comment]
Does the browser say `Connected` in the console?

**Comment by FranklinChen** [comment]
Yes, it does say `Connected`. But I see that in the console in Firefox 54.0 on macOS, before that output, there is

```
TypeError: navigator.webkitGetUserMedia is not a function
```

It works fine in Google Chrome! Could it be made portable to work on Firefox also then?

**Comment by paf31** [comment]
I suspect we just need a polyfill for the various names `webkitGetUserMedia` has. Would you be able to make a PR?

Something like

```js
navigator.getUserMedia = 
  navigator.getUserMedia ||
  navigator.webkitGetUserMedia ||
  navigator.mozGetUserMedia;
```

(what MDN recommends) should do it.
